### ISSUE TITLE
Documentation update checklist for future releases

### ISSUE THREAD

**Issue by jmhogan** [cernopendata/cms-opendata-guide#113]
Making a big checklist! Program lives in this Google doc and was presented in DPOA on 9/25/30. 

EMPTY pages to fill:
- [ ] Triggers: Start by summarizing and linking to workshop lessons
- [ ] Luminosity: Get Brilcalc examples, they exist. Try to remove dropdown and have it as one page
- [ ] Backgrounds: port section by Julie from EXO-23-006 here as a starting point
- [ ] Interpretation: port workshop lessons / CMSDAS / Julie's EXO-23-006 summary for concepts. PyHF for calculation, as in #10 
- [ ] Systematics:
   - [ ] Lumi uncertainties: grab info and pubs from ~any of our papers
   - [ ] MC uncertainty:  port Julie's info from EXO-23-006 as a starting point
   - [ ] Pileup uncertainty: grab info from pubs / TWikis. For 2016 this lives in correctionLib. For 2015 find docs
   - [ ] Lepton/photon uncertainties: write a basic description. For 2016 these are all in correctionLib. For 2015 and earlier find docs.
   - [ ] **Idea to put a correctionLib instruction page here**

Pages to rework / remove / big update:
- [ ] FAQ: port things from the "troubleshooting" portal page over here, since we have better control over this repo for edits
- [ ] Systematics --> Jet uncertainties: update into **tabs** for AOD/Mini/Nano, reference correctionLib for 2016.
- [ ] Physics Objects: update into **tabs** for AOD/Mini/Nano and add new 2016 info. Do the "to-do"s in the pages
- [ ] ID Efficiency Study: port most of this into a workshop-connected Carpentries site. Keep tag-and-probe basic information and introduce the corrections based on efficiency that are detailed in Systematics. T&P would be the main way people can calc their own SFs.
- [ ] Unix: add WSL2 box info with the notes about avoiding Git Bash for future container use.

Pages needing small updates / tweaks:
- [ ] Finding Data: update workshop link and/or give multiple
- [ ] ROOT: check links and provide a workshop lesson link
- [ ] Docker: port intro explanations from the VM page. Amp up the tabs by linking workshop lessons
- [ ] Data Model: eventually add 2016 and NanoAOD
- [ ] Analyzer: add links to workshop lessons for Run 1 / Run 2 EDM files. Note POET 2011 vs 2012 branches. Eventually add 2016 info
- [ ] Configuration: same notes as above
- [ ] Conditions Data: check the examples for anything out of date. Expand the info at the bottom to include Run 2
- [ ] Collision Data: can the warning label go?
- [ ] MC Simulations: watch for cross section updates to the record pages and describe them here
- [ ] Event Generation: update the example to show production of Mini and Nano from AOD.
- [ ] About: add more contributor names.
