### ISSUE TITLE
General Staff Checklist

### ISSUE THREAD

**Issue by caredg** [cernopendata/cms-opendata-guide#20]
While not the heart of the documentation, important to fill out:

- [ ] Write a brief introduction to the guide (front page)
- [ ] Write the How to use this guide section in the front page
- [ ] Take care of the FAQ
- [ ] Take care of the About section
