### ISSUE TITLE
Computing tools checklist

### ISSUE THREAD

**Issue by katilp** [cernopendata/cms-opendata-guide#4]
To-do list for the first section "Computing tools".
None of these topics needs new example code.
In the list below, possible links to existing documentation which can be included to the text.

- [ ] Check if the current subsections are sufficient
  - do we need unix, bash?
- [ ] CERN Open Data Portal 
  - can link to http://opendata.cern.ch/docs/about , else?
- [ ] CMS Open Data
  - can link to http://opendata.cern.ch/docs/about-cms , else ?
- [ ] CMS Twiki
  - can link to https://twiki.cern.ch/twiki/bin/view/CMSPublic/WorkBook
- [ ] ROOT
  - a link to root tutorial?
- [ ] C++ and Python
  - a link HEP related tutorial
   - python, check later with https://indico.cern.ch/event/882660/timetable/ else?
   - C++ 
- [ ] Git
  - a link to http://swcarpentry.github.io/git-novice/
- [ ] Docker
  - a link to https://awesome-workshop.github.io/intro-to-docker/ (not all relevant)
  - CMS OD specific http://opendata.cern.ch/docs/cms-guide-docker
- [ ] Virtual Machines
  - a link to http://opendata.cern.ch/docs/cms-virtual-machine-2011

**Comment by caredg** [comment]
I have added a UNIX section

**Comment by jieunyoo** [comment]
I am checking off the "CMS Twiki" page although it has been removed per the suggestion here: https://github.com/cernopendata/cms-opendata-guide/issues/34
