### ISSUE TITLE
Analysis checklist

### ISSUE THREAD

**Issue by katilp** [cernopendata/cms-opendata-guide#7]
To-do list for the section "Analysis".
The topics can link to an existing analysis, eg to https://github.com/cms-opendata-analyses/HiggsTauTauNanoAODOutreachAnalysis (or its future extended version) or to to  to show an example
In the list below, possible links to existing documentation which can be included to the text.

- Data and Simulation 
  - [ ] Write a brief introduction
  - [ ] Collision Data: describe content, dataformat, dataset names, where to get these data 
         according to different releases
  - [ ] MC Simulations: this refers to datasets, which are simulation.  Same idea as describing collision data. See http://opendata.cern.ch/docs/cms-mc-production-overview
      - [ ] Here we should describe what pile-up is
  - [ ] Event Generation: this refers to doing reconstruction of data (marginal) and doing MC simulations.  See http://opendata.cern.ch/docs/cms-guide-event-production
  
- Selection
      It should flow as in a real analysis and there the first thing, generally, is to deal with the trigger (an object by itself, basically), so it needs this #16 fix.
  - [ ] Write a brief introduction
  - [ ] Triggers: Explain what the trigger system is, how it works in CMS and how to extract the information with a few examples.  See http://opendata.cern.ch/docs/cms-guide-trigger-system
     - Implement an explain different available examples.  See https://github.com/cms-legacydata-analyses/TriggerInfoTool.  Maybe they will need separate pages in the doc. #17
     - [ ] Guide on general trigger information
     - [ ] Guide on getting prescales
     - [ ] Guide on how to get trigger objects and info
     - [ ] Guide on the basics of trigger matching
    - see suggestion in the context of the HTT example in #11
  - [ ] Objects: Describe or point to description of what physical objects are at the different levels if possible, i.e., mc truth, reco.
     - Here we can use the PhysicsOjectExtractorTool.  See https://github.com/cms-legacydata-analyses/PhysObjectExtractorTool  #18 
  - [ ] Object ID (here we can separate in different objects #19)
    - [ ] Muons
    - [ ] Electrons
    - [ ] Jet
    - [ ] Met
    - [ ] Muons
    - [ ] Photons
    - [ ] Taus
  - [ ] Additional corrections   
    - jet energy correction 
      - for MC (@slaurila) :  it would be best to apply the [JEC]( https://twiki.cern.ch/twiki/bin/view/CMS/JECDataMC#Jet_Energy_Corrections_in_Run1) already at the stage of NanoAOD production, and store the corrected jets as a separate collection. For future, I think it would be useful to store the JEC uncertainties in the NanoAOD as well. After the corrections are in the NanoAOD, applying them should be straightforward (just switch to the other jet collection) and this would also allow coparisons between corrected and non-corrected jets at the analysis stage. 
    - muon scale and momentum corrections (see #13)
    - electron scale and momentun corrections
    - tau (@slaurila): according to [Tau POG]( https://twiki.cern.ch/twiki/bin/view/CMS/TauIDRecommendation), neither tau ID nor the energy scale needs a correction by default
  
- [ ] Luminosity
- Backgrounds
  - [ ] Techniques
  - [ ] QCD Estimation
   - for the example code suggestion see #9
  - [ ] Upper-limit Calculations
- Systematics
  - @slaurila: Ideally, there would be recipes for estimating at least the dominating syst. uncertainties and including them in the results. But again, adding the machinery for full systematics treatment (running different variations of the analysis for shape systematics, combining them into uncertainty bands in plots, etc) will probably make the code considerably more complex, unless there is some new smart way of dealing with all of this RDataFrame..
  - [ ] Luminosity Uncertainties
  - [ ] MC Uncertainty
  - [ ] Object Uncertainty
  - [ ] Pileup Uncertainty
   - for the example code see #8
- Interpretation
  - [ ] Statistics
   - for a suggestions and consideration see
